[
{"teks":" Frases da Bíblia:\n\nFelizes são os que ouvem a palavra de Deus e a guardam!\n(Lucas 11:28)"},
{"teks":" Frases ds Bíblia:\n\nNão amemos de palavras nem de língua, mas por ações e em verdade."},
{"teks":" Frases da Bíblia:\n\nSe Cristo vos libertar, verdadeiramente sereis livres.\n(João 8:36)"},
{"teks":" Frases da Bíblia:\n\nO meu mandamento é este: amem uns aos outros como eu amo vocês.\n(João 15:12)"},
{"teks":" Frases da Bíblia:\n\nLavo as minhas mãos na inocência; e assim andarei, Senhor, ao redor do teu altar. Para publicar com voz de louvor, e contar todas as tuas maravilhas.\n(Salmos 26:6,7)"},
{"teks":" Frases da Bíblia:\n\nFica longe das discussões e evitarás o pecado, porque o homem colérico atiça a discussão."},
{"teks":" Frases da Bíblia:\n\nToda a educação, no momento, não parece motivo de alegria, mas de tristeza. Depois, no entanto, produz naqueles que assim foram exercitados um fruto de paz e de justiça."},
{"teks":" Frases da Bíblia:\n\nQuem é correto nunca fracassará e será lembrado para sempre."},
{"teks":" Frases da Bíblia:\n\nFelizes são aqueles que não se deixam levar pelos conselhos dos maus."},
{"teks":" Frases da Bíblia:\n\nO ódio provoca dissensão, mas o amor cobre todos os pecados."},
{"teks":" Frases da Bíblia:\n\nO Senhor é o meu pastor, nada me faltará.\nSalmo 23"},
{"teks":" Frases da Bíblia:\n\nQuem semeia a injustiça colherá a desgraça."},
{"teks":" Frases da Bíblia:\n\nDeus converte o deserto em lago e a terra seca em fontes."},
{"teks":" Frases da Bíblia:\n\nMais vale um homem lento à cólera do que um herói, e um homem senhor de si do que o conquistador de uma cidade."},
{"teks":" Frases da Bíblia:\n\nA falta de coração despreza o seu próximo."},
{"teks":" Frases da Bíblia:\n\nCada qual mente ao seu próximo, falando com lábios fluentes e duplo coração."},
{"teks":" Frases da Bíblia:\n\nTu que estás lá nas alturas, assim mesmo te interesses pelos humildes."},
{"teks":" Frases da Bíblia:\n\nUm corpo corruptível pesa sobre a alma e - tenda de argila - oprime a mente pensativa."},
{"teks":" Frases da Bíblia:\n\nOra, a fé é a certeza de coisas que se esperam, a convicção de fatos que não se veem.\nHebreus 11:1"},
{"teks":" Frases da Bíblia:\n\nFazei justiça ao fraco e ao órfão, procedei retamente para com o aflito e o desamparado.\nSalmos"},
{"teks":" Frases da Bíblia:\n\nAinda que eu andasse pelo vale da sombra da morte, não temeria mal algum, porque tu estás comigo.\n(Salmos 23:4)"},
{"teks":" Frases da Bíblia:\n\nPorque eu, o SENHOR, teu Deus, te tomo pela tua mão direita e te digo: não temas, que eu te ajudo."},
{"teks":" Frases da Bíblia:\n\nQuem não se ama não sabe amar os outros."},
{"teks":" Frases da Bíblia:\n\nSim, eu amo Deus. Ele é a fonte de minha existência, é meu Salvador. Ele me sustenta a cada dia. Sem Ele eu não sou nada, mas com Ele eu posso todas as coisas através de Jesus Cristo, que me fortalece.\nBíblia"},
{"teks":" Frases da Bíblia:\n\nEntreguem todas as suas preocupações a Deus, pois ele cuida de vocês.\nBíblia"},
{"teks":" Frases da Bíblia:\n\nDeus limpará de seus olhos todas as lágrimas.\nBíblia"},
{"teks":" Frases da Bíblia:\n\nO nome de Deus é, realmente, magnífico! Tu não temerás os terrores noturnos, nem a flecha que voa à luz do dia. Nenhum mal te atingirá.\nBíblia"},
{"teks":" Frases da Bíblia:\n\nAgora, pois, permanecem a fé, a esperança e o amor, estes três, mas o maior destes é o amor.\nBíblia Sagrada"},
{"teks":" Frases da Bíblia:\n\nNenhuma condenação há para os que estão em Cristo Jesus\nBíblia Sagrada"},
{"teks":" Frases da Bíblia:\n\nBuscai ao Senhor enquanto se pode achar, invocai-o enquanto está perto.\nBíblia"},
{"teks":" Frases da Bíblia:\n\nO amor cobrirá a multidão de pecados.\nBíblia"},
{"teks":" Frases da Bíblia:\n\nComo flechas na mão do guerreiro, assim os filhos da mocidade.\nSalmos"},
{"teks":" Frases da Bíblia:\n\nPor isso, não fiquem preocupados com o dia de amanhã, pois o dia de amanhã trará as suas próprias preocupações. Para cada dia bastam as suas próprias dificuldades.\n(Mateus 6:34)"},
{"teks":" Frases da Bíblia:\n\nNada há encoberto que não haja de revelar-se, nem oculto que não haja de saber-se.\n(Mateus 10:26)"},
{"teks":" Frases da Bíblia:\n\nPortanto, não percam a coragem, pois ela traz uma grande recompensa.\nBíblia Sagrada"},
{"teks":" Frases da Bíblia:\n\nE sabemos que todas as coisas contribuem juntamente para o bem daqueles que amam a Deus, daqueles que são chamados por seu decreto.\nBíblia Sagrada"},
{"teks":" Frases da Bíblia:\n\nTu, porém, quando orares, entra no teu quarto e, fechada a porta, orarás a teu Pai, que está em secreto; e teu Pai, que vê em secreto, te recompensará.\n (Mateus 6:6)"},
{"teks":" Frases da Bíblia:\n\nEu vim para que tenham vida e a tenham em abundância.\nBíblia"},
{"teks":" Frases da Bíblia:\n\nNão sabeis que sois santuário de Deus e que o seu Espírito habita em vós? Se alguma pessoa destruir o santuário de Deus, este o destruirá; pois o santuário de Deus, que sois vós, é sagrado.\nBíblia"},
{"teks":" Frases da Bíblia:\n\nNão extingais o Espírito. Não desprezeis as profecias. Examinai tudo. Retende o bem.\nBíblia"},
{"teks":" Frases da Bíblia:\n\nE guiar-te-ei com meus próprios olhos.\nBíblia"},
{"teks":" Frases da Bíblia:\n\nAquele que não quer trabalhar que também não coma.\nBíblia"},
{"teks":" Frases da Bíblia:\n\nFaçam aos outros o que vocês querem que eles façam a vocês.\nBíblia Sagrada"},
{"teks":" Frases da Bíblia:\n\nAnda com os sábios e serás sábio, mas o companheiro dos tolos será afligido.\nBíblia"},
{"teks":" Frases da Bíblia:\n\nO choro pode durar uma noite, mas a alegria vem pela manhã.\n(Salmos 30:5)"},
{"teks":" Frases da Bíblia:\n\nO nosso socorro está em o nome do Senhor, criador do céu e da Terra.\nSalmo 124:8"},
{"teks":" Frases da Bíblia:\n\nO Senhor é o meu pastor, nada me faltará.\n(Salmo 23.1)"},
{"teks":" Frases da Bíblia:\n\nLâmpada para os meus pés é a tua palavra e, luz para os meus caminhos.\n(Salmos 119:105)"},
{"teks":" Frases da Bíblia:\n\nEntrega o teu caminho ao Senhor; confia nele, e ele tudo fará.\n(Salmos 37:5)"},
{"teks":" Frases da Bíblia:\n\nNem olhos viram, nem ouvidos ouviram, nem jamais penetrou o coração humano, o que Deus tem preparado para aqueles que O amam.\n"},
{"teks":" Frases da Bíblia:\n\nO amor é paciente, o amor é bondoso. Não inveja, não se vangloria, não se orgulha. (...) Tudo sofre, tudo crê, tudo espera, tudo suporta. (...) Assim, permanecem agora estes três: a fé, a esperança e o amor. O maior deles, porém, é o amor.\nBíblia"},
{"teks":" Frases da Bíblia:\n\nCria em mim, ó Deus, um coração puro, e renova em mim um espírito reto.\nSalmos"},
{"teks":" Frases da Bíblia:\n\nAmor tudo sofre,tudo crê,tudo espera,tudo suporta,o amor jamais acaba.\nApóstolo Paulo"},
{"teks":" Frases da Bíblia:\n\nCritica o tolo, e ele te odiará, critica o sábio, e ele te amará.\nBíblia"},
{"teks":" Frases da Bíblia:\n\nNão há nada escondido que não venha a ser revelado, nem oculto que não venha a se tornar conhecido.\nMateus 10:26"},
{"teks":" Frases da Bíblia:\n\nSenhor, como são numerosos os meus perseguidores!Mas vós sois, Senhor, para mim um escudo;Eu, que me tenho deitado e adormecido,Levanto-me, porque o Senhor me sustenta.\n(Salmos 3)"},
{"teks":" Frases da Bíblia:\n\nAquele que não ama não conhece a Deus; porque Deus é amor.\nBíblia Sagrada"},
{"teks":" Frases da Bíblia:\n\nAs más companhias corrompem os bons costumes.\nBíblia Sagrada"},
{"teks":" Frases da Bíblia:\n\nAinda que a minha mente e o meu corpo enfraqueçam, Deus é a minha força, Ele é tudo o que eu sempre preciso.\nSalmos 73:26"},
{"teks":" Frases da Bíblia:\n\nNão esqueçais que o verdadeiro perdão se reconhece pelos atos, muito mais que pelas palavras.\nApóstolo Paulo"},
{"teks":" Frases da Bíblia:\n\nMas Deus dá prova do seu amor para conosco, em que, quando éramos ainda pecadores, Cristo morreu por nós.\nApóstolo Paulo"},
{"teks":" Frases da Bíblia:\n\nQuanto ao mais, irmãos, tudo o que é verdadeiro, tudo o que é honesto, tudo o que é justo, tudo o que é puro, tudo o que é amável, tudo o que é de boa fama, se há alguma virtude, e se há algum louvor, nisso pensai.\nBíblia Sagrada"},
{"teks":" Frases da Bíblia:\n\nNão mais vivo eu, mas cristo vive em mim.\nApóstolo Paulo"},
{"teks":" Frases da Bíblia:\n\nFelizes são os que ajudam os pobres, pois o Senhor Deus os ajudará quando estiverem em dificuldades.\nBíblia"},
{"teks":" Frases da Bíblia:\n\nNão te deixes vencer pelo mal, mas vence o mal com o bem.\nBíblia Sagrada"},
{"teks":" Frases da Bíblia:\n\nAgrada-te do Senhor, e Ele satisfará os desejos do teu coração.\n(Salmos 37:4)"},
{"teks":" Frases da Bíblia:\n\nTudo sofre, tudo crê, tudo espera, tudo suporta. O amor jamais acaba; havendo profecias, desaparecerão; havendo línguas, cessarão; havendo ciências, passarão.Agora, pois permanecem a fé, a esperança e o Amor. Porém o maior deste é o Amor.\nBíblia"},
{"teks":" Frases da Bíblia:\n\nIsto é o que vos peço, que vosso amor cresça cada vez mais.\nBíblia Sagrada"},
{"teks":" Frases da Bíblia:\n\nNão recuarei, nada temerei, comigo está o Senhor!\nBíblia"},
{"teks":" Frases da Bíblia:\n\nPor isso posso me deitar tranquilo e dormir em paz. Quando acordo, me sinto seguro, porque Deus cuida de mim.\n(Salmos 3:5)"},
{"teks":" Frases da Bíblia:\n\nPorque a boca fala o de que está cheio o coração.\n(Mateus 12:34)"},
{"teks":" Frases da Bíblia:\n\nQuero trazer à memória o que me pode dar esperança.\nBíblia"},
{"teks":" Frases da Bíblia:\n\nO amigo fiel é uma forte proteção, e quem o achou, achou um tesouro.\nBíblia"},
{"teks":" Frases da Bíblia:\n\nTodos que se levantarão contra ti, com mentiras e traições. E estando você com a verdade, serão confundidos e envergonhados.\nBíblia"},
{"teks":" Frases da Bíblia:\n\nTenham amor, pois o amor une perfeitamente todas as coisas. O amor é o vínculo da perfeição.\nBíblia"},
{"teks":" Frases da Bíblia:\n\nPõe-me como selo sobre o teu coração, como selo sobre o teu braço, porque o amor é forte como a morte.\n(Cântico 8:6)"},
{"teks":" Frases da Bíblia:\n\nA doçura no falar aumenta o saber."},
{"teks":" Frases da Bíblia:\n\nEm paz me deito e logo pego no sono, porque, Senhor, só tu me fazes repousar seguro.\n(Salmos 4:8)"},
{"teks":" Frases da Bíblia:\n\nO Senhor é a minha luz e a minha salvação; de quem terei medo? O Senhor é a fortaleza da minha vida; a quem temerei?\nBíblia Sagrada"},
{"teks":" Frases da Bíblia:\n\nCorrija um sábio e o fará mais sábio. Corrija um tolo e o fará teu inimigo."}
]

